const trades=["ROOFING","PLUMBING","ELECTRICAL","HVAC","FENCING","BUILDING","LANDSCAPING"];
const services=[["Google Ads","Get found when customers are ready to hire."],["Meta Ads","Create demand in your local service area."],["Websites","Turn traffic into genuine enquiries."],["Lead Follow-Up","Stop good leads slipping through the cracks."],["SEO","Build long-term local visibility."]];
export default function Home(){return <main>
<header><a className="brand" href="#"><b>monsta</b><i>Miami</i></a><nav><a href="#how">How it works</a><a href="#services">Services</a><a href="#proof">Results</a></nav><a className="btn" href="#contact">GET MORE JOBS →</a></header>
<section className="hero"><div className="copy"><span className="eyebrow">DIGITAL MARKETING FOR TRADIES</span><h1><em>MORE JOBS.</em><br/>LESS CHASING.</h1><h2>Marketing built for businesses that work with their hands.</h2><p>We help tradies get found, generate enquiries and turn more of those enquiries into real work.</p><a className="btn big" href="#contact">SHOW ME THE OPPORTUNITY →</a></div><div className="visual"><div className="ring"></div><div className="stamp">BUILT FOR<br/><strong>TRADIES</strong></div></div></section>
<div className="trades">{trades.map(x=><span key={x}>{x}</span>)}</div>
<section id="how" className="split"><div><span className="eyebrow">YOUR JOB PIPELINE</span><h3>DON'T JUST BUY LEADS.<br/><em>FIX THE LEAKS.</em></h3><p>Getting an enquiry is only the start. We look at the full path from search to phone call, quote and job won — so your marketing isn't judged by clicks, but by opportunities for real work.</p></div><div className="pipeline"><div className="steps"><b>ENQUIRY</b><i>→</i><b>CONTACT</b><i>→</i><b>QUOTE</b><i>→</i><b>JOB</b></div><h4>Where are potential jobs slipping away?</h4><p>We'll look at how customers find you, what happens after they enquire and where the biggest opportunity sits.</p><a className="white" href="#contact">SHOW ME THE OPPORTUNITY →</a></div></section>
<section id="services" className="section"><span className="eyebrow">WHAT WE DO</span><h3>WE BUILD YOUR <em>JOB PIPELINE.</em></h3><p className="lead">Different tools. One goal: more quality opportunities for your business.</p><div className="cards">{services.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h4>{a}</h4><p>{b}</p></article>)}</div></section>
<section id="proof" className="proof"><span className="eyebrow">PROOF, NOT HYPE</span><h3>REAL TRADIES.<br/><em>REAL RESULTS.</em></h3><p>We won't fill this page with invented percentages or fake testimonials. As Monsta Miami campaigns go live, verified results will live here — the numbers that actually matter to tradies.</p><div className="metrics"><div><b>LEADS</b><span>Qualified enquiries</span></div><div><b>QUOTES</b><span>Real opportunities</span></div><div><b>JOBS</b><span>Work won</span></div></div></section>
<section id="contact" className="contact"><div><span className="eyebrow">LET'S TALK</span><h3>GOOD AT YOUR TRADE?<br/><em>WE'LL HANDLE THE MARKETING.</em></h3><p>Tell us what you do and where you work. We'll start with the opportunity — not a sales pitch.</p></div><form><label>WHAT TRADE ARE YOU IN?</label><select defaultValue=""><option value="" disabled>Select your trade</option>{trades.map(x=><option key={x}>{x}</option>)}</select><label>WHERE DO YOU WORK?</label><input placeholder="Suburb / service area"/><label>BEST NUMBER TO REACH YOU</label><input type="tel" placeholder="Phone number"/><button type="button">SHOW ME THE OPPORTUNITY →</button><small>No spam. No obligation.</small></form></section>
<footer><a className="brand" href="#"><b>monsta</b><i>Miami</i></a><p>Digital marketing built for tradies.</p></footer>
</main>}